const symptoms = [
  'Headache',
  'Fever',
  'Fatigue',
  'Cough',
  'Sore throat',
  'Runnynose',
  'Body ache',
  'Nasal congestion',
  'Neck pain',
  'Dizziness',
  'Loss of Apetite',
  'Go',
];

const fullSymptomList = [
  'Headache',
  'Fever',
  'Fatigue',
  'Cough',
  'Sore throat',
  'Runnynose',
  'Body ache',
  'Nasal congestion',
  'Neck pain',
  'Dizziness',
  'Loss of Apetite',
  'Chest pain',
  'Changes in Urination',
  'Mood swings',
  'Shortness of breath',
  'Swelling',
  'Difficulty sleeping',
  'Night sweats',
  'Disorientation',
  'Abdominal pain',
  'Weight loss',
  '',
  '',
  '',
];

export { symptoms, fullSymptomList };
