const symptoms = [
  'Headache',
  'Fever',
  'Fatigue',
  'Cough',
  'Sore throat',
  'Runnynose',
  'Body ache',
  'Nasal congestion',
  'Neck pain',
  'Dizziness',
  'Loss of Appetite',
  'Go!',
];

const fullSymptomList = [
  'Headache',
  'Fever',
  'Fatigue',
  'Cough',
  'Sore throat',
  'Runnynose',
  'Body ache',
  'Nasal congestion',
  'Neck pain',
  'Dizziness',
  'Loss of Appetite',
  'Chest pain',
  'Changes in Urination',
  'Mood swings',
  'Shortness of breath',
  'Swelling',
  'Difficulty sleeping',
  'Night sweats',
  'Disorientation',
  'Abdominal pain',
  'Weight loss',
  '',
  '',
  '',
];

const healthConsultants = [
  'Generate a record keeping template',
  'Diagnosis and treatment analysis',
  'All about breast cancer',
  'All about breast cancer',
  'Diagnosis and treatment analysis',
  'Generate a record keeping template',
  'Generate a record keeping template',
  'Diagnosis and treatment analysis',
  'All about breast cancer',
  '',
  '',
  '',
];

export { symptoms, fullSymptomList, healthConsultants };
